words:
  - betterstack
  - biome
  - biomejs
  - clsx
  - cmdk
  - embla
  - emblor
  - grek
  - hono
  - hookform
  - lucide
  - lucide-react
  - neondatabase
  - nextjs
  - openapi
  - packagejson
  - pageleave
  - pageview
  - posthog
  - sonner
  - tanstack
  - trivago
  - turbopack
  - typecheck
  - ultracite
  - vaul
  - whsec
  - whyleonardo
