import type {
  ForwardRefExoticComponent,
  JSX,
  RefAttributes,
  SVGProps,
} from "react"

import { Icons } from "@/components/icons"

import {
  ActivityIcon,
  AirplayIcon,
  AlertCircleIcon,
  AlertOctagonIcon,
  AlertTriangleIcon,
  AlignCenterIcon,
  AlignJustifyIcon,
  AlignLeftIcon,
  AlignRightIcon,
  AnchorIcon,
  ApertureIcon,
  ArchiveIcon,
  ArrowDownCircleIcon,
  ArrowDownIcon,
  ArrowDownLeftIcon,
  ArrowDownRightIcon,
  ArrowLeftCircleIcon,
  ArrowLeftIcon,
  ArrowRightCircleIcon,
  ArrowRightIcon,
  ArrowUpCircleIcon,
  ArrowUpDownIcon,
  ArrowUpIcon,
  ArrowUpLeftIcon,
  ArrowUpRightIcon,
  AtSignIcon,
  AwardIcon,
  BarChart2Icon,
  BarChartIcon,
  BatteryChargingIcon,
  BatteryIcon,
  BellIcon,
  BellOffIcon,
  BluetoothIcon,
  BoldIcon,
  BookIcon,
  BookOpenIcon,
  BookmarkIcon,
  BotIcon,
  BoxIcon,
  BriefcaseIcon,
  BrushIcon,
  CalendarIcon,
  CameraIcon,
  CameraOffIcon,
  CaseLowerIcon,
  CastIcon,
  CheckCircleIcon,
  CheckIcon,
  CheckSquareIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChevronsDownIcon,
  ChevronsLeftIcon,
  ChevronsRightIcon,
  ChevronsUpIcon,
  CircleIcon,
  ClipboardIcon,
  ClockIcon,
  CloudDrizzleIcon,
  CloudIcon,
  CloudLightningIcon,
  CloudOffIcon,
  CloudRainIcon,
  CloudSnowIcon,
  CodeIcon,
  CodeXmlIcon,
  CommandIcon,
  CompassIcon,
  ConeIcon,
  CopyIcon,
  CornerDownLeftIcon,
  CornerDownRightIcon,
  CornerLeftDownIcon,
  CornerLeftUpIcon,
  CornerRightDownIcon,
  CornerRightUpIcon,
  CornerUpLeftIcon,
  CornerUpRightIcon,
  CpuIcon,
  CreditCardIcon,
  CropIcon,
  CrosshairIcon,
  DatabaseIcon,
  DeleteIcon,
  DiscIcon,
  DollarSignIcon,
  DownloadCloudIcon,
  DownloadIcon,
  DropletIcon,
  Edit2Icon,
  Edit3Icon,
  EditIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FacebookIcon,
  FastForwardIcon,
  FeatherIcon,
  FileIcon,
  FileMinusIcon,
  FilePlusIcon,
  FileTextIcon,
  FilmIcon,
  FilterIcon,
  FlagIcon,
  FolderIcon,
  FolderMinusIcon,
  FolderPlusIcon,
  GiftIcon,
  GitBranchIcon,
  GitCommitIcon,
  GitMergeIcon,
  GitPullRequestIcon,
  GithubIcon,
  GitlabIcon,
  GlobeIcon,
  GridIcon,
  HardDriveIcon,
  HashIcon,
  HeadphonesIcon,
  HeartIcon,
  HelpCircleIcon,
  HomeIcon,
  ImageIcon,
  InboxIcon,
  InfoIcon,
  InstagramIcon,
  ItalicIcon,
  KeyIcon,
  LayersIcon,
  LayoutIcon,
  LifeBuoyIcon,
  Link2Icon,
  LinkIcon,
  LinkedinIcon,
  ListIcon,
  LockIcon,
  LogInIcon,
  LogOutIcon,
  type LucideProps,
  MailIcon,
  MapIcon,
  MapPinIcon,
  Maximize2Icon,
  MaximizeIcon,
  MenuIcon,
  MessageCircleIcon,
  MessageSquareIcon,
  MicIcon,
  MicOffIcon,
  Minimize2Icon,
  MinimizeIcon,
  MinusCircleIcon,
  MinusIcon,
  MinusSquareIcon,
  MonitorIcon,
  MoonIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  MoveIcon,
  MusicIcon,
  Navigation2Icon,
  NavigationIcon,
  OctagonIcon,
  PackageIcon,
  PackageOpenIcon,
  PaletteIcon,
  PanelsTopLeftIcon,
  PaperclipIcon,
  PauseCircleIcon,
  PauseIcon,
  PercentIcon,
  PhoneCallIcon,
  PhoneForwardedIcon,
  PhoneIcon,
  PhoneIncomingIcon,
  PhoneMissedIcon,
  PhoneOffIcon,
  PhoneOutgoingIcon,
  PieChartIcon,
  PlayCircleIcon,
  PlayIcon,
  PlusCircleIcon,
  PlusIcon,
  PlusSquareIcon,
  PocketIcon,
  PowerIcon,
  PrinterIcon,
  RadioIcon,
  RefreshCcwIcon,
  RefreshCwIcon,
  RepeatIcon,
  RewindIcon,
  RotateCcwIcon,
  RotateCwIcon,
  RssIcon,
  SaveIcon,
  ScissorsIcon,
  SearchIcon,
  SendIcon,
  ServerIcon,
  SettingsIcon,
  Share2Icon,
  ShareIcon,
  ShieldIcon,
  ShieldOffIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  ShuffleIcon,
  SidebarIcon,
  SkipBackIcon,
  SkipForwardIcon,
  SlackIcon,
  SlashIcon,
  SlidersIcon,
  SmartphoneIcon,
  SpeakerIcon,
  SquareIcon,
  StarIcon,
  StopCircleIcon,
  SunIcon,
  SunriseIcon,
  SunsetIcon,
  TabletIcon,
  TagIcon,
  TargetIcon,
  TerminalIcon,
  ThermometerIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  ToggleLeftIcon,
  ToggleRightIcon,
  Trash2Icon,
  TrashIcon,
  TriangleIcon,
  TruckIcon,
  TvIcon,
  TwitterIcon,
  TypeIcon,
  UmbrellaIcon,
  UnderlineIcon,
  UnlockIcon,
  UploadCloudIcon,
  UploadIcon,
  UserCheckIcon,
  UserIcon,
  UserMinusIcon,
  UserPlusIcon,
  UserXIcon,
  UsersIcon,
  VideoIcon,
  VideoOffIcon,
  VoicemailIcon,
  Volume1Icon,
  Volume2Icon,
  VolumeIcon,
  VolumeXIcon,
  WatchIcon,
  WifiIcon,
  WifiOffIcon,
  WindIcon,
  XCircleIcon,
  XIcon,
  XSquareIcon,
  YoutubeIcon,
  ZapIcon,
  ZapOffIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from "lucide-react"

export type TagIconOption = keyof typeof tagIconsOptions

export type Icon = (
  props: SVGProps<SVGSVGElement>
) =>
  | JSX.Element
  | ForwardRefExoticComponent<
      Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>
    >

export const tagIconsOptions = {
  activity: ActivityIcon,
  airplay: AirplayIcon,
  "alert-circle": AlertCircleIcon,
  "alert-octagon": AlertOctagonIcon,
  "alert-triangle": AlertTriangleIcon,
  "align-center": AlignCenterIcon,
  "align-justify": AlignJustifyIcon,
  "align-left": AlignLeftIcon,
  "align-right": AlignRightIcon,
  anchor: AnchorIcon,
  aperture: ApertureIcon,
  archive: ArchiveIcon,
  "arrow-down": ArrowDownIcon,
  "arrow-down-circle": ArrowDownCircleIcon,
  "arrow-down-left": ArrowDownLeftIcon,
  "arrow-down-right": ArrowDownRightIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-left-circle": ArrowLeftCircleIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-right-circle": ArrowRightCircleIcon,
  "arrow-up": ArrowUpIcon,
  "arrow-up-circle": ArrowUpCircleIcon,
  "arrow-up-down": ArrowUpDownIcon,
  "arrow-up-left": ArrowUpLeftIcon,
  "arrow-up-right": ArrowUpRightIcon,
  at: AtSignIcon,
  award: AwardIcon,
  "bar-chart": BarChartIcon,
  "bar-chart-2": BarChart2Icon,
  battery: BatteryIcon,
  "battery-charging": BatteryChargingIcon,
  bell: BellIcon,
  "bell-off": BellOffIcon,
  bluetooth: BluetoothIcon,
  bold: BoldIcon,
  book: BookIcon,
  "book-open": BookOpenIcon,
  bookmark: BookmarkIcon,
  box: BoxIcon,
  bot: BotIcon,
  briefcase: BriefcaseIcon,
  brush: BrushIcon,
  calendar: CalendarIcon,
  camera: CameraIcon,
  "camera-off": CameraOffIcon,
  "case-lower": CaseLowerIcon,
  cast: CastIcon,
  check: CheckIcon,
  "check-circle": CheckCircleIcon,
  "check-square": CheckSquareIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-up": ChevronUpIcon,
  "chevrons-down": ChevronsDownIcon,
  "chevrons-left": ChevronsLeftIcon,
  "chevrons-right": ChevronsRightIcon,
  "chevrons-up": ChevronsUpIcon,
  circle: CircleIcon,
  clipboard: ClipboardIcon,
  clock: ClockIcon,
  cloud: CloudIcon,
  "cloud-drizzle": CloudDrizzleIcon,
  "cloud-lightning": CloudLightningIcon,
  "cloud-off": CloudOffIcon,
  "cloud-rain": CloudRainIcon,
  "cloud-snow": CloudSnowIcon,
  code: CodeIcon,
  "code-xml": CodeXmlIcon,
  command: CommandIcon,
  compass: CompassIcon,
  cone: ConeIcon,
  copy: CopyIcon,
  "corner-down-left": CornerDownLeftIcon,
  "corner-down-right": CornerDownRightIcon,
  "corner-left-down": CornerLeftDownIcon,
  "corner-left-up": CornerLeftUpIcon,
  "corner-right-down": CornerRightDownIcon,
  "corner-right-up": CornerRightUpIcon,
  "corner-up-left": CornerUpLeftIcon,
  "corner-up-right": CornerUpRightIcon,
  cpu: CpuIcon,
  "credit-card": CreditCardIcon,
  crop: CropIcon,
  crosshair: CrosshairIcon,
  database: DatabaseIcon,
  delete: DeleteIcon,
  disc: DiscIcon,
  dollar: DollarSignIcon,
  download: DownloadIcon,
  "download-cloud": DownloadCloudIcon,
  droplet: DropletIcon,
  edit: EditIcon,
  "edit-2": Edit2Icon,
  "edit-3": Edit3Icon,
  "external-link": ExternalLinkIcon,
  eye: EyeIcon,
  "eye-off": EyeOffIcon,
  facebook: FacebookIcon,
  "fast-forward": FastForwardIcon,
  feather: FeatherIcon,
  file: FileIcon,
  "file-minus": FileMinusIcon,
  "file-plus": FilePlusIcon,
  "file-text": FileTextIcon,
  film: FilmIcon,
  filter: FilterIcon,
  flag: FlagIcon,
  folder: FolderIcon,
  "folder-minus": FolderMinusIcon,
  "folder-plus": FolderPlusIcon,
  gift: GiftIcon,
  "git-branch": GitBranchIcon,
  "git-commit": GitCommitIcon,
  "git-merge": GitMergeIcon,
  "git-pull-request": GitPullRequestIcon,
  github: GithubIcon,
  gitlab: GitlabIcon,
  globe: GlobeIcon,
  grid: GridIcon,
  hard: HardDriveIcon,
  hash: HashIcon,
  headphones: HeadphonesIcon,
  heart: HeartIcon,
  "help-circle": HelpCircleIcon,
  home: HomeIcon,
  image: ImageIcon,
  inbox: InboxIcon,
  info: InfoIcon,
  instagram: InstagramIcon,
  italic: ItalicIcon,
  key: KeyIcon,
  layers: LayersIcon,
  layout: LayoutIcon,
  "life-buoy": LifeBuoyIcon,
  link: LinkIcon,
  "link-2": Link2Icon,
  linkedin: LinkedinIcon,
  list: ListIcon,
  lock: LockIcon,
  "log-in": LogInIcon,
  "log-out": LogOutIcon,
  mail: MailIcon,
  map: MapIcon,
  "map-pin": MapPinIcon,
  maximize: MaximizeIcon,
  "maximize-2": Maximize2Icon,
  menu: MenuIcon,
  "message-circle": MessageCircleIcon,
  "message-square": MessageSquareIcon,
  mic: MicIcon,
  "mic-off": MicOffIcon,
  minimize: MinimizeIcon,
  "minimize-2": Minimize2Icon,
  minus: MinusIcon,
  "minus-circle": MinusCircleIcon,
  "minus-square": MinusSquareIcon,
  monitor: MonitorIcon,
  moon: MoonIcon,
  "more-horizontal": MoreHorizontalIcon,
  "more-vertical": MoreVerticalIcon,
  move: MoveIcon,
  music: MusicIcon,
  navigation: NavigationIcon,
  "navigation-2": Navigation2Icon,
  octagon: OctagonIcon,
  package: PackageIcon,
  "package-open": PackageOpenIcon,
  palette: PaletteIcon,
  panels: PanelsTopLeftIcon,
  paperclip: PaperclipIcon,
  pause: PauseIcon,
  "pause-circle": PauseCircleIcon,
  percent: PercentIcon,
  phone: PhoneIcon,
  "phone-call": PhoneCallIcon,
  "phone-forwarded": PhoneForwardedIcon,
  "phone-incoming": PhoneIncomingIcon,
  "phone-missed": PhoneMissedIcon,
  "phone-off": PhoneOffIcon,
  "phone-outgoing": PhoneOutgoingIcon,
  "pie-chart": PieChartIcon,
  play: PlayIcon,
  "play-circle": PlayCircleIcon,
  plus: PlusIcon,
  "plus-circle": PlusCircleIcon,
  "plus-square": PlusSquareIcon,
  pocket: PocketIcon,
  power: PowerIcon,
  printer: PrinterIcon,
  radio: RadioIcon,
  "refresh-ccw": RefreshCcwIcon,
  "refresh-cw": RefreshCwIcon,
  repeat: RepeatIcon,
  rewind: RewindIcon,
  rotate: RotateCcwIcon,
  "rotate-cw": RotateCwIcon,
  rss: RssIcon,
  save: SaveIcon,
  scissors: ScissorsIcon,
  search: SearchIcon,
  send: SendIcon,
  server: ServerIcon,
  settings: SettingsIcon,
  shadcn: Icons.shadcn,
  share: ShareIcon,
  "share-2": Share2Icon,
  shield: ShieldIcon,
  "shield-off": ShieldOffIcon,
  "shopping-bag": ShoppingBagIcon,
  "shopping-cart": ShoppingCartIcon,
  shuffle: ShuffleIcon,
  sidebar: SidebarIcon,
  "skip-back": SkipBackIcon,
  "skip-forward": SkipForwardIcon,
  slack: SlackIcon,
  slash: SlashIcon,
  sliders: SlidersIcon,
  smartphone: SmartphoneIcon,
  speaker: SpeakerIcon,
  square: SquareIcon,
  star: StarIcon,
  "stop-circle": StopCircleIcon,
  sun: SunIcon,
  sunrise: SunriseIcon,
  sunset: SunsetIcon,
  tablet: TabletIcon,
  tag: TagIcon,
  target: TargetIcon,
  terminal: TerminalIcon,
  thermometer: ThermometerIcon,
  "thumbs-down": ThumbsDownIcon,
  "thumbs-up": ThumbsUpIcon,
  "toggle-left": ToggleLeftIcon,
  "toggle-right": ToggleRightIcon,
  trash: TrashIcon,
  "trash-2": Trash2Icon,
  triangle: TriangleIcon,
  truck: TruckIcon,
  tv: TvIcon,
  twitter: TwitterIcon,
  type: TypeIcon,
  umbrella: UmbrellaIcon,
  underline: UnderlineIcon,
  unlock: UnlockIcon,
  upload: UploadIcon,
  "upload-cloud": UploadCloudIcon,
  user: UserIcon,
  "user-check": UserCheckIcon,
  "user-minus": UserMinusIcon,
  "user-plus": UserPlusIcon,
  "user-x": UserXIcon,
  users: UsersIcon,
  video: VideoIcon,
  "video-off": VideoOffIcon,
  voicemail: VoicemailIcon,
  volume: VolumeIcon,
  "volume-1": Volume1Icon,
  "volume-2": Volume2Icon,
  "volume-x": VolumeXIcon,
  watch: WatchIcon,
  wifi: WifiIcon,
  "wifi-off": WifiOffIcon,
  wind: WindIcon,
  x: XIcon,
  "x-circle": XCircleIcon,
  "x-square": XSquareIcon,
  youtube: YoutubeIcon,
  zap: ZapIcon,
  "zap-off": ZapOffIcon,
  "zoom-in": ZoomInIcon,
  "zoom-out": ZoomOutIcon,
} as const
